# Generated by Django 4.2.7 on 2023-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=5000)),
                ('image_link', models.CharField(max_length=5000)),
                ('url_link', models.CharField(max_length=5000)),
                ('sambol', models.CharField(max_length=5000)),
            ],
        ),
    ]
