# Generated by Django 4.2.7 on 2023-11-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_product_image_link_alter_product_url_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_link',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_link',
            new_name='url',
        ),
    ]
